# ============================================================================
# Codex CLI — Comprehensive Configuration Template
# Generated: 2025-08-27
#  ~/.codex/config.toml (aka $CODEX_HOME/config.toml)
# ============================================================================

model = "gpt-5-codex"                                # default model
approval_policy = "never"                  # "untrusted" | "on-failure" | "on-request" | "never"
sandbox_mode = "danger-full-access"                      # "read-only" | "workspace-write" | "danger-full-access"
file_opener = "cursor"                          # "vscode" | "vscode-insiders" | "windsurf" | "cursor" | "none"
model_reasoning_effort = "high"               # "minimal" | "low" | "medium" | "high" | "none"

notify = ["/bin/sh", "-c", "afplay /System/Library/Sounds/Funk.aiff"]

[tools]
web_search = true

[history]
persistence = "save-all"          # "save-all" | "none"

[mcp_servers.figma]
command = "npx"
args = ["figma-developer-mcp", "--stdio"]
env = { FIGMA_API_KEY = "" }

[mcp_servers.serena]
command = "uvx"
args = ["--from", "git+https://github.com/oraios/serena", "serena", "start-mcp-server", "--context", "codex"]

[chrome-devtools]
command = "npx"
args = ["chrome-devtools-mcp@latest"]
